[package]
name = "Quad-FEM-Showcase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
nalgebra-sparse = "0.9.0"
mshio = "0.4.2"
vtkio = "0.6.3"